#!/sbin/bb/busybox ash
#
# lkflash - flash latest leanKernel
# 
# author - imoseyon@gmail.com
#
BB="/sbin/bb/busybox"
subdir="grouper"

CUR=`$BB uname -a | $BB awk -F- '{ print \$4 }'`
DEVICE=`$BB uname -a | $BB awk -F- '{ print \$3 }'`
STABLE="http://imoseyon.host4droid.com/${subdir}/lkflash/${DEVICE}"

$BB mkdir -p /sdcard/lk

while [ 1 ]; do
echo
echo "leanKernel flasher"
echo "------------------"
echo "1) latest stable (recommended)"
echo "3) check/display versions" 
echo
echo "FLASH AT YOUR OWN RISK. I'm not responsible for my mistakes or yours. ;)"
echo
echo -n "Please enter a number between 1 and 3 (or press enter to exit): "

read option
case $option in
  1)
	$BB wget -q -O /sdcard/lk/loc $STABLE
	echo; echo -n "Downloading stable "
	break
	;;
  2) 
	break
	;;
  3) 
  	echo "Please wait..."
	vstable=`$BB wget -q -O - $STABLE | $BB awk '{ print \$3 }'`
	echo; echo ">>> Current version: $CUR, Latest stable: $vstable"	
	sleep 2
	;;
  *)
	echo "BYE"
	exit
	;;
esac
done

[ ! -s "/sdcard/lk" ] && exit
MD5=`$BB awk '{ print \$2 }' /sdcard/lk`
VER=`$BB awk '{ print \$3 }' /sdcard/lk`
if [ "$CUR" == "$VER" ]; then
  echo
  echo "Aborted. You're already running $CUR."
  exit
fi
echo "v$VER. Please wait..."
$BB wget -q -O /sdcard/lkboot.img `$BB awk '{ print \$1 }' /sdcard/lk`
[ ! -s "/sdcard/lkboot.img" ] && exit
SUM=`$BB md5sum /sdcard/lkboot.img | $BB awk '{ print \$1 }'`
echo
if [ "$MD5" == "$SUM" ]; then
  echo "Download finished. Checksum verified. Flashing kernel to boot partition..."
  $BB dd if=/sdcard/lkboot.img of=/dev/block/platform/sdhci-tegra.3/by-name/LNX 2> /dev/null
  echo; echo "leanKernel $VER flashed!  Reboot when you're ready to run new kernel."
else
  echo "md5sum check failed - please try again."
fi

